fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    inifile:
      repo: 'git://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: '1.5.0'
    hocon:
      repo: 'git://github.com/puppetlabs/puppetlabs-hocon.git'
      ref: '0.9.4'
  symlinks:
    puppet: "#{source_dir}"
